version: '3.1'
services:     
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Ammy@123
    volumes:
     - ./data.sql:/docker-entrypoint-initdb.d/data.sql
  
   