apiVersion: v1
kind: Service
metadata:
  name: demo2-service
spec:
  selector: 
    app: label2-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30001